### ISSUE TITLE
Could not run example

### ISSUE THREAD

**Issue by haosdent** [mesos/mesos-go#105]
Hello, I start mesos with local mode. And I meet this error when start executor:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0309 16:45:43.719032 2064278272 fetcher.cpp:76] Fetching URI 'http://127.0.0.1:12345/executor'
I0309 16:45:43.719732 2064278272 fetcher.cpp:126] Downloading 'http://127.0.0.1:12345/executor' to '/tmp/mesos/0/slaves/20150309-160300-16777343-5050-66790-S0/frameworks/20150309-162423-16777343-5050-67747-0005/executors/default/runs/55cbff65-f05f-4df8-bea0-caffe52c474c/executor'E0309 16:45:43.720167 2064278272 fetcher.cpp:129] Error downloading resource: Couldn't connect to server
Failed to fetch: http://127.0.0.1:12345/executor
```

But I am sure scheduler is start and server files in 12345.

**Comment by fmpwizard** [comment]
Hi,

can you run `ls` from the same place you start the scheduler and can you also paste here the full command you are using to start the scheduler?

Also, the error message shows that the file name that it is trying to download is `executor`, but according to the build instructions on the README, the file is actually `test-executor`

That may be the issue, that you specified a different executor file name.

**Comment by haosdent** [comment]
I change the name in example.
```
 ~/workspace/go/mesos-tutorial/src   master ●  ls -1executor*
executor.go
executor_test.go
scheduler*
scheduler.go
scheduler_test.go
``

**Comment by haosdent** [comment]
Is the slave start executor in sandbox and it coudn't fetch the url?

**Comment by fmpwizard** [comment]
what's the full command you used to start the scheduler?

>Is the slave start executor in sandbox and it coudn't fetch the url?

the only time I got this error before was then I misspelled the scecutor's name when starting the scheduler, so it failed to fetch the file, because it was looking for the wrong filename

**Comment by haosdent** [comment]
I start it with
```
./scheduler --master=127.0.0.1:5050 --executor=/Users/haosdent/workspace/go/mesos-tutorial/src/executor --logtostderr=true
```

**Comment by haosdent** [comment]
And I start mesos in local mode:

```
mesos-local --ip=127.0.0.1 --port=5050 --log_dir=/tmp
```

**Comment by fmpwizard** [comment]
hm, that looks right, maybe there is something in the logs from the scheduler, does it show that it is serving files on port 12345 ?

When you start the scheduler, add this parameter `-v=2` that should enable this line to printout the path it is serving:
`log.V(2).Infof("Hosting artifact '%s' at '%s'", path, hostURI)`

from https://github.com/mesos/mesos-go/blob/master/examples/test_framework.go#L208

so run:

```
./scheduler \
--master=127.0.0.1:5050 \
--executor=/Users/haosdent/workspace/go/mesos-tutorial/src/executor \
--logtostderr=true \
-v=2
```

**Comment by haosdent** [comment]
OK, let me try.
And I add change the uri to "http://www.google.com", still could not connect in slave.

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0309 17:41:29.120925 2064278272 fetcher.cpp:76] Fetching URI 'http://www.google.com'
E0309 17:41:29.121604 2064278272 fetcher.cpp:121] Malformed URL (missing path)
Failed to fetch: http://www.google.com
```

**Comment by haosdent** [comment]
But my machine could connect google success.
```
/tmp/mesos/0/slaves  curl http://www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.sg/?gfe_rd=cr&amp;ei=M2v9VPn0NOmW8Qf3voGAAw">here</A>.
</BODY></HTML>
```

**Comment by fmpwizard** [comment]
note this:

>Malformed URL (missing path)

if you want to try downloading some file to see if that works, try something like
https://github.com/lift/lift_26_sbt/tarball/master

that will download a tar file

But let's see what the logging says after adding -v=2

**Comment by haosdent** [comment]
I got this:
```
Hosting artifact '/Users/haosdent/workspace/go/mesos-tutorial/src/executor' at 'http://127.0.0.1:12345/executor'
```

**Comment by haosdent** [comment]
Oh, I could download robots.txt.
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0309 17:47:58.824838 2064278272 fetcher.cpp:76] Fetching URI 'http://www.google.com/robots.txt'
I0309 17:47:58.825623 2064278272 fetcher.cpp:126] Downloading 'http://www.google.com/robots.txt' to '/tmp/mesos/0/slaves/20150309-174054-16777343-5050-14015-S0/frameworks/20150309-174054-16777343-5050-14015-0004/executors/default/runs/ade0ed55-c07d-4557-88da-7521734b8e88/robots.txt'
```

So the bug in my program, not from mesos. Let me find it. Thank you very much.

**Comment by fmpwizard** [comment]
locally I actually don't include the full path to the file, I simply do:

`-execcutor=executor-name-here` nit sure if that would make a diff there.

**Comment by haosdent** [comment]
Thank you for your help, I find the problem now. :-)
