### ISSUE TITLE
The location of executor stdout

### ISSUE THREAD

**Issue by haosdent** [mesos/mesos-go#106]
Hello, when I run example, I could not find the stdout of executor in log. Where are them output?

For example, I use 
```
fmt.Println("Start ExampleExecutor")
fmt.Fprintf(os.Stderr, "Hello\n")
```

And I could not found them in `/tmp/mesos/0/slaves/20150309-212927-16777343-5050-18580-S0/frameworks/20150309-212927-16777343-5050-18580-0008/executors/default/runs/latest/stderr` and `/tmp/mesos/0/slaves/20150309-212927-16777343-5050-18580-S0/frameworks/20150309-212927-16777343-5050-18580-0008/executors/default/runs/latest/stdout`.

**Comment by fmpwizard** [comment]
I see them on the terminal where I started mesos from (I use the `bin/mesos-local.sh` script) I haven't looked into the setting that would send them to the places you are listing.

**Comment by haosdent** [comment]
Thank you for your great help! :+1:

**Comment by haosdent** [comment]
Is it possible I redirect the output of executor to the "stdout" file? @fmpwizard Thank you in advance.

**Comment by haosdent** [comment]
Oh, got it. Run it with mesos-master and mesos-slave.
