### ISSUE TITLE
scheduler incorrectly unregisters framework that intends to failover

### ISSUE THREAD

**Issue by jdef** [mesos/mesos-go#109]
from scheduler/scheduler.go:
```go
	if driver.connected && failover {
		// unregister the framework
```

the condition should check for `!failover`, just like the C++ version does:
https://github.com/apache/mesos/blob/0.22.0/src/sched/sched.cpp#L837

```c
    if (connected && !failover) {
      UnregisterFrameworkMessage message;
```

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/167

**Comment by vladimirvivien** [comment]
Fixed by @jdef
