### ISSUE TITLE
Can't compile without mesos headers installed in system root

### ISSUE THREAD

**Issue by bretthoerner** [mesos/mesos-go#12]
Compilation seems to assume I have mesos headers installed in `/usr/local/include`, is it possible to compile with mesos installed elsewhere? This may be more of a Go problem than a mesos-go one, but the folks in #mesos asked me to make a ticket for now.

```
$ go get github.com/mesosphere/mesos-go/example_framework
# github.com/mesosphere/mesos-go/mesos
.go/src/github.com/mesosphere/mesos-go/mesos/executor_driver.cpp:5:30: fatal error: mesos/executor.hpp: No such file or directory
 #include <mesos/executor.hpp>
                              ^
compilation terminated.
```

**Comment by vladimirvivien** [comment]
Closing as project no longer depend on c-based api.
