### ISSUE TITLE
format of MasterInfo stored in ZK nodes will change in mesos v0.24

### ISSUE THREAD

**Issue by jdef** [mesos/mesos-go#141]
From the user/dev mailing list:
> Folks,
> 
> as heads-up, we are planning to convert the format of the MasterInfo
> information stored in ZooKeeper from the Protocol Buffer binary format to
> JSON - this is in conjunction with the HTTP API development, to allow
> frameworks *not* to depend on libmesos and other binary dependencies to
> interact with Mesos Master nodes.
> 
> *NOTE* - there is no change in 0.23 (so any Master/Slave/Framework that is
> currently working in 0.22 *will continue to work* in 0.23 too) but as of
> Mesos 0.24, frameworks and other clients relying on the binary format will
> break.
> 
> The details of the design are in this Google Doc:
> https://docs.google.com/document/d/1i2pWJaIjnFYhuR-000NG-AC1rFKKrRh3Wn47Y2G6lRE/edit
> 
> the actual work is detailed in MESOS-2340:
> https://issues.apache.org/jira/browse/MESOS-2340
> 
> and the patch (and associated test) are here:
> https://reviews.apache.org/r/35571/
> https://reviews.apache.org/r/35815/

**Comment by tsenart** [comment]
0.24 is coming out very soon, this needs to be prioritised.

**Comment by jdef** [comment]
Did we already pass the deprecation cycle? Protobuf for master info is
completely gone in v0.24?

**Comment by jdef** [comment]
should be fixed by #174
