### ISSUE TITLE
Http transports blocks for messages sent after a master died but before failover

### ISSUE THREAD

**Issue by sttts** [mesos/mesos-go#155]
**Context:** Kubernetes on Mesos scheduler

The scheduler blocks while reregistering and does not survive Mesos master failover most of the times. 

A log is shown in this gist: https://gist.github.com/sttts/fd66462513f6630aeeb7. Also compare https://github.com/GoogleCloudPlatform/kubernetes/issues/12281.

**Analysis:** The scheduler's http client is blocked by a message sent to the master after the master failed, but before the scheduler knew about that. In the case of the log above it takes several seconds until a "No route to host" error is returned. During this time, the scheduler cannot reregister with the master, i.e. the `ReregisterFrameworkMessage` messages are actually never sent.

Eventually the timeout happens and the "No route to host" error is shown. Unfortunately the Kubernetes scheduler terminates due to this. The example_scheduler recovers.

**Test case:** The same blocking http sending queue can be triggered by adding a `time.Sleep(3*time.Second)` to the `ResourceOffers` function of `example_scheduler.go`. Start this scheduler against e.g. a 3 master Mesos setup with Zookeeper URLs and shutdown the active master. If the `LaunchTasks` message is sent before the scheduler notices the dead master, i.e. before `zk.EventNodeChildrenChanged` is shown, the following reregistrations will fail.

**Comment by jdef** [comment]
fixed by #221
