### ISSUE TITLE
Question on HTTP vs Protobuf

### ISSUE THREAD

**Issue by zrml** [mesos/mesos-go#161]
Hi: in the description it says it's an HTTP implementation, however, I only see protobufs being used...
Could you please explain? I'm confused as the HTTP REST API is not available yet till v0.24 which is not yet released...
thank you for your time.

**Comment by tsenart** [comment]
We're using the internal Mesos HTTP APIs with Protobuf payloads.

**Comment by zrml** [comment]
OK so this is still a protobuf implementation... there is no official demo in the Mesos 0.24 REST API.
Right?

**Comment by jdef** [comment]
To be clear, mesos-go currently attempts to implement the libprocess
message passing protocol, which abuses HTTP.
The HTTP API v1 that's being introduced in v0.24 has no mesos-go analogue.
Some prototyping was being done here:
https://github.com/jimenez/mesoscon-demo (but this is really a toy).

**Comment by zrml** [comment]
and we need Mesos 0.24... OK; Thanks jdef.

**Comment by jdef** [comment]
The "official" reference (
https://docs.google.com/document/d/1pnIY_HckimKNvpqhKRhbc9eSItWNFT-priXh_urR-T0/edit#heading=h.ej7mjb84f6x9)
actually links somewhere else.. https://github.com/jimenez/mesos-APIproto

Apologies for the misdirection

**Comment by zrml** [comment]
no trouble; I met Isabel at MesosCon in Seattle and had a chat... thanks a lot!

**Comment by zrml** [comment]
jdef: do you know if there is a beta of Mesos master 0.24 (better if dockerized) that I can start playing with to test that API please?
Thanks again

**Comment by jdef** [comment]
There's an RC2 release that people are voting on.

https://dist.apache.org/repos/dist/dev/mesos/0.24.0-rc2/mesos-0.24.0.tar.gz

**Comment by zrml** [comment]
Great news! Thanks jdef! Cool :)
