### ISSUE TITLE
please include copyright attribution

### ISSUE THREAD

**Issue by onlyjob** [mesos/mesos-go#163]
Currently there is no copyright attribution anywhere in this source tree. Only license grant is present which says:

> See the NOTICE file distributed with this work for additional information  regarding copyright ownership.

However `NOTICE` file is nowhere to be found.

Please add copyright attribution, perhaps something like

    Copyright 2013-2015 The Apache Software Foundation

Thanks.

**Comment by tsenart** [comment]
@jdef: Do you know  why this is the case? We have a LICENSE at the root of the repo.

**Comment by jdef** [comment]
The fact that there is no NOTICE file is likely an oversight. The project
is Apache licensed, and the license says that there's a NOTICE file. We
should probably add one.

**Comment by tsenart** [comment]
What goes in the NOTICE file?

**Comment by jdef** [comment]
Something like this:

```
Mesos Go
Copyright 2013, The Apache Software Foundation
```

**Comment by tsenart** [comment]
Hmm, but it's not part of the ASF. It's Mesosphere's.

**Comment by jdef** [comment]
forwarding to legal

**Comment by onlyjob** [comment]
Thanks but shouldn't it be "2013-2015" instead of just 2015? Development did not  begin this year I presume...

**Comment by tsenart** [comment]
@onlyjob: Done in 5b109eedd4b017e6eaf134cb8da1e25f7e2ed3f1. Thanks!

**Comment by onlyjob** [comment]
Thanks! :)
