### ISSUE TITLE
Rename import paths to github.com/mesosphere org

### ISSUE THREAD

**Issue by tsenart** [mesos/mesos-go#172]
After having migrated this repo from github.com/mesos to github.com/mesosphere, we need to adjust the import paths.

Importers of this library will still work with both as far as they have this library vendored.

**Comment by jdef** [comment]
Given that other mesos client libs may be introduced to github.com/mesos,
is it still reasonable to relocate this project?

**Comment by tsenart** [comment]
Hm, I don't see an advantage. I think the mesos org is actually confusing people in regards to ownership and governance. Under mesosphere that isn't the case.

**Comment by jdef** [comment]
Sounds like something that should be run up the ladder. Whatever we do with
mesos-go should be consistent with what is going to happen with the rest of
the upcoming client libs

**Comment by tsenart** [comment]
That's a fair point. I'll migrate it back to the mesos org.
