### ISSUE TITLE
generate protobufs for mesos-0.24

### ISSUE THREAD

**Issue by jdef** [mesos/mesos-go#191]
systems like mesos-dns (and even our own master-detection stuff) need access to things like MasterInfo.Address messages.

xref https://github.com/mesosphere/mesos-dns/issues/291

**Comment by tsenart** [comment]
Hm, I though I had done this in the last release. It seems I did regenerate the code with a more recent protoc plugin but didn't update the protobufs themselves.

**Comment by tsenart** [comment]
We need to retag mesos-v0.24.0 after we did this.
