### ISSUE TITLE
Framework Restart Problems

### ISSUE THREAD

**Issue by kellrott** [mesos/mesos-go#199]
I'm working on a new framework, and of course making mistakes. The problem is that my framework's registration sticks around after the scheduler exits, and the next time I try to start the scheduler, its unable to start. Right now the only solution seems to be to restart mesos and its workers.

On the error 
```
I1025 18:12:30.856917   29383 scheduler.go:1012] Stopping the scheduler driver
I1025 18:12:30.856921   29383 scheduler.go:1062] stopping messenger
I1025 18:12:30.856926   29383 messenger.go:269] stopping messenger..
I1025 18:12:30.856930   29383 http_transporter.go:476] stopping HTTP transport
I1025 18:12:30.856933   29383 scheduler.go:1065] Stop() complete with status DRIVER_STOPPED error <nil>
```

When I try to restart

```
I1025 18:13:27.168331   29393 scheduler.go:323] Initializing mesos scheduler driver
I1025 18:13:27.168403   29393 scheduler.go:792] Starting the scheduler driver...
I1025 18:13:27.168453   29393 http_transporter.go:407] listening on 127.0.0.1 port 55059
I1025 18:13:27.168462   29393 scheduler.go:809] Mesos scheduler driver started with PID=scheduler(1)@127.0.0.1:55059
I1025 18:13:27.170233   29393 scheduler.go:374] New master master@127.0.0.1:5050 detected
I1025 18:13:27.170242   29393 scheduler.go:435] No credentials were provided. Attempting to register scheduler without authentication.
I1025 18:13:27.170908   29393 scheduler.go:1081] Aborting framework [&FrameworkID{Value:*agro,XXX_unrecognized:[],}]
I1025 18:13:27.170949   29393 messenger.go:269] stopping messenger..
I1025 18:13:27.170954   29393 http_transporter.go:476] stopping HTTP transport
```

Shouldn't mesos-go be better about restarting a framework, or cleaning up one?

**Comment by jdef** [comment]
what parameters are you configuring your framework with? are you setting your own framework ID? (i see `*agro` in your logs)

**Comment by kellrott** [comment]
Yes. I was setting my own framework ID. The example I was working from did that as well. If I remove that, a UUID is assigned, and I can do the start a new framework. 
Is it possible to resume/restart a framework (if there are active slaves working)?

**Comment by jdef** [comment]
Yes it is possible.You should set a reasonable failover timeout (2 weeks?
maybe longer) and enable checkpointing for the framework and for the
slaves. Your framework is responsible for persisting the originally
assigned framework ID so that it may be recovered in the event of a
scheduler failure. Upon scheduler restart, provide the framework ID that
mesos originally assigned you in the first Registered() callback. The
master will recognize that your scheduler has restarted. Your tasks will
continue to run, uninterrupted.
