### ISSUE TITLE
master build is broken in Travis CI

### ISSUE THREAD

**Issue by s-urbaniak** [mesos/mesos-go#207]
https://travis-ci.org/mesos/mesos-go/builds/89106214
xfref https://github.com/mesos/mesos-go/pull/200

**Comment by johnweldon** [comment]
Addressed in pull request #252 with commit 42cb9a81acb3012d25a48d0bc8834a1a509c95bb

**Comment by jdef** [comment]
fixed by #252

**Comment by johnweldon** [comment]
I'm not sure my PR actually fixed this issue - the build failure looked different.  I was too quick to link the two before verifying they were the same root issue.
