### ISSUE TITLE
"MESOS_SLAVE_PID" Missing

### ISSUE THREAD

**Issue by mehiar** [mesos/mesos-go#215]
Hi,

I am getting the following error:
"failed to initialize the driver: Cannot find MESOS_SLAVE_PID in the environment. Unable to create a ExecutorDriver  Cannot find MESOS_SLAVE_PID in the environment" 
every time I run a go executor on a Mesos slave. I was wondering what I need to do to set those env variables. Thanks in advance for your help.

Regards,
Mehiar

**Comment by jdef** [comment]
what version of mesos are you using? are you invoking your executor on the command-line directly, or are you letting it be invoked via a slave containerizer?

**Comment by mehiar** [comment]
I am using Mesos version 0.25.0 and I am invoking my executor directly from the command-line.

**Comment by jdef** [comment]
ok, executors are intended to be run by a mesos slave containerizer which is expected to provide the missing env var. for testing you can try running the executor from the command line and provide the missing env var, but that's not a supported way to run things.
