### ISSUE TITLE
Mesos Go does not detected mesos master restart

### ISSUE THREAD

**Issue by doronp** [mesos/mesos-go#231]
Hi,

I bumped into this:
https://github.com/mesosphere/kubernetes-mesos/issues/344

And also:
https://github.com/docker/swarm/issues/1730

Was wondering if there is any intention to fix this issue 

Thanks,
Doron P

**Comment by jdef** [comment]
Which mesos master detector is being used? ZK? standalone?

**Comment by doronp** [comment]
@jdef So sorry I missed your response.

In the second thread - in Swarm there is no use of ZK at all.

In the first one You should know better I think.

**Comment by doronp** [comment]
@jdef Do you consider any fix with regards of this issue? Tnx.

**Comment by jdef** [comment]
I've considered fixes for this. The standalone implementation needs love to be more production ready. And if you're in production .. when why run a standalone master? Seems like asking for trouble. Or am I misunderstanding the situation? Is this blocking production deployments?

**Comment by jdef** [comment]
Reiterating: the standalone implementation is not robust or production ready. Please use ZK for reliably detecting master failover.

If you're interested in detecting network partitions, the v1 API has heartbeat detection built-in
