### ISSUE TITLE
[Propsal] mesos-go talks to Multiple Mesos Masters

### ISSUE THREAD

**Issue by dhilipkumars** [mesos/mesos-go#234]
Hi All,

We use mesos-go for a couple of our projects and it is really useful. 

We have a requirement to make the framework written using golang binding talk to multiple masters at the same time. 
![mesos-go](https://cloud.githubusercontent.com/assets/10920260/14522113/9a657e0c-024a-11e6-8f30-14f3c72df1a0.png)

We tried with creating multiple driver objects 

```
go func() {
if stat1, err1 := driver1.Run(); err != nil {
        log.Infof("Framework stopped with status %s and error: %s\n", stat.String(), err1.Error())
        time.Sleep(2 * time.Second)
        os.Exit(1)
    }
}()

go func() {
if stat2, err2 := driver2.Run(); err != nil {
        log.Infof("Framework stopped with status %s and error: %s\n", stat.String(), err2.Error())
        time.Sleep(2 * time.Second)
        os.Exit(1)
    }
}()
.
.

```

for the same scheduler object, we get offers from all the master to the same call backs which is really convenient but what we want to know is that will there be scope for potential race conditions by doing so?

Could we make mesos-go natively talk to multiple Masters? If yes what is the effort you foresee  in this project?

We would like to volunteer in this effort and raise a PR as this is really important to us. What we really appreciate is some sort of basic design document of this project that you had at the time of writing this repo and some directions of where to start. 

We did spend a couple of days on this but the mesos-go is reasonably complex any help would be awesome for us to get started with.

@jdef 

Thanks in Advance,
Dhilip

**Comment by spacejam** [comment]
Are you asking for a single driver to support multiple mesos masters, or to ensure that multiple drivers can exist without interfering with any global state? Multiple masters is fairly unusual, but the latter option should be straightforward if it's not already supported (basically just grep for global var's and see what uses them, and make them non-global, and you should be set).

If you're asking for multiple master support with a single driver, what generic use cases do you imagine would be better served with this than just having two drivers?  Distributed systems are full of failures, fault domains multiply when composed, and reconciliation of multiple faulty clusters in a partially-applied state is an annoying problem to deal with (tons of complexity, and as you said, mesos-go is complex enough).

**Comment by jdef** [comment]
There's no reason that a single process couldn't connect to multiple mesos masters. This is probably easier to deal with using the APIs in the "next" branch (also see #274). By design a Mesos framework only connects to a single master; that said, a single process could spin up multiple embedded frameworks if desired. You'd just need to keep your events organized so that you're not communicating with master2 about events from master1.

**Comment by dhilipkumars** [comment]
@jdef  Thanks fro the response we solved this by creating multiple drivers, that was pretty straight forward
