### ISSUE TITLE
Idiomatic way to get at task sandbox / logs?

### ISSUE THREAD

**Issue by wrouesnel** [mesos/mesos-go#243]
Possibly slightly peripheral to the main issues of Mesos bindings, but when writing schedulers a standard pattern would certainly be to interact with the sandbox and stdout/stderr files in particular?

It would be helpful if there was an idiomatic interface in the bindings for doing this - the HTTP only focus of the `next` branch might work in this capacity?

**Comment by jdef** [comment]
Thanks for bringing this up! It's possible. I briefly considered prototyping support for the other (non-v1) endpoints. Needs more thought. And it's a lower priority than making the v1 scheduler/executor API usable.

**Comment by jdef** [comment]
"Mesos v1 HTTP Operator API" https://docs.google.com/document/d/1XfgF4jDXZDVIEWQPx6Y4glgeTTswAAxw6j8dPDAtoeI/edit?pref=2&pli=1

**Comment by jdef** [comment]
several people have asked about maintenance / operator APIs, including #265
