### ISSUE TITLE
Would there be API changes in `next`?

### ISSUE THREAD

**Issue by cannium** [mesos/mesos-go#245]
I'm considering to build a framework based on mesos-go `master` branch, and want to know if `next` would break current APIs.

**Comment by jdef** [comment]
Thanks for bringing this up! As it stands now the APIs are quite different. There's been some discussion re: a portability layer that would support frameworks that have already built upon the callback-style APIs of master. It seems pretty clear that having such would benefit existing frameworks. That said, even if there was a portability layer that presented a very similar API it may not be an API that's 100% backward compatible so I'd expect some breakage - it's just a question of how much.

**Comment by jdef** [comment]
#274
