### ISSUE TITLE
Question: AcceptOffers got "403 Forbidden"

### ISSUE THREAD

**Issue by weiwei04** [mesos/mesos-go#257]
I build a small mesos cluster(1 master 1 slave) use docker to run the persistent_scheduler in mesos-go/examples/persistent_scheduler and got a "403 Forbidden" error when scheduler send AcceptOffers.
I read the mesos-go code and the [scheduler api doc](http://mesos.apache.org/documentation/latest/scheduler-http-api/), to use /api/v1/scheduler api, driver should first send a Call_SUBSCRIBE message, and use another connection to send subsequent Call_ACCEPT message.
`Scheduler must make additional HTTP requests to the “/scheduler” endpoint only after it has opened a persistent connection to it by sending a SUBSCRIBE request and received a SUBSCRIBED response. Calls made without subscription will result in a “403 Forbidden” instead of a “202 Accepted” response.` 
seems mesos-go driver use a RegisterFrameworkMessage to register with mesos instead of SUBSCRIBE, is there a plan to fix problem?

======================================
my test env
ubuntu 14.04
docker version 1.11.1

docker run -d -e MESOS_HOSTNAME=127.0.0.1 -e MESOS_IP=127.0.0.1 -e MESOS_PORT=5051 -e MESOS_MASTER=127.0.0.1:5050 -e MESOS_RESOURCES="cpus:1.2" -v /sys/fs/cgroup:/sys/fs/cgroup -v /var/run/docker.sock:/var/run/docker.sock --name slave --net host --privileged mesoscloud/mesos-slave:0.28.1-ubuntu-14.04

docker run -d -e MESOS_HOSTNAME=127.0.0.1 -e MESOS_IP=127.0.0.1 -e MESOS_PORT=5050 --name mesos-master --net host --restart always mesoscloud/mesos-master:0.28.1-ubuntu-14.04

**Comment by jdef** [comment]
It sounds like you're using the code on mesos-go/master (uses the older, mesos v0 API) but you're reading the mesos docs for the newer v1 API. The mesos-go project has been building support for the v1 API in the mesos-go/next branch. That branch is currently under development, so please vendor appropriately. There is also example code in that branch that demos how to use the new API.
