### ISSUE TITLE
Question: How to compile the source code into the RPM package

### ISSUE THREAD

**Issue by mgdsxhy** [mesos/mesos-go#259]
Hi, I need a help!
Because of a specific requirements, We have modified the part mesos source code. 
Now have a question: How to compile the source code into the RPM package???

or if you can provide the offficial rpm build spec file

**Comment by bbannier** [comment]
Have a look into the tools in https://github.com/mesosphere/mesos-deb-packaging.

**Comment by mgdsxhy** [comment]
Hi, bbannier. We have tried, but failed.   enviroment: Centos7
Are there any other solutions?

**Comment by mgdsxhy** [comment]
Thanks, We get it!
