### ISSUE TITLE
AcceptOffers got "403 Forbidden" status

### ISSUE THREAD

**Issue by anywhy** [mesos/mesos-go#266]
Use mesos version: `1.0.1`
Build a small mesos cluster(1 master 1 slave) to run the persistent_scheduler in mesos-go/examples/persistent_scheduler and got a "403 Forbidden" error when scheduler send AcceptOffers.
```
E1105 17:49:47.195893    8606 messenger.go:318] failed to send message "scheduler": master master@127.0.0.1:5050 rejected /api/v1/scheduler, returned status "403 Forbidden"
```

**Comment by povilasv** [comment]
I tried to launch the same persistent_scheduler and also reproduced this error.
When trying to debug this using tcpdump I found that  "403 Forbidden" error returns with message:
**Framework is not connected via HTTP**

**Comment by athlum** [comment]
@anywhy `mesos-1.0.1` uses `v1 Scheduler HTTP API`
Use the `next` branch with https://github.com/mesos/mesos-go/pull/263.

**Comment by jdef** [comment]
the v1 API has landed on master, please use that
