### ISSUE TITLE
Proto support for mesos 1.1.0

### ISSUE THREAD

**Issue by athlum** [mesos/mesos-go#270]
Hi @jdef , `mesos 1.1.0` comes with the `LaunchGroup` feature.
It's there any plan on update proto files to mesos 1.1.x?

How do you think about LaunchGroup, is it production ready?
Thanks.

**Comment by kevinschoon** [comment]
Hi -- 

I [updated](https://github.com/vektorlab/mesos-go/tree/updates) the next branch against the v1 protobufs in Mesos [1.1.x](https://github.com/apache/mesos/tree/1.1.x) albeit somewhat painstakingly..

All the tests pass and I am able to get it to work some trivial scheduler code however the code in `cmd/example-*` still needs to be updated.

Would appreciate any feedback on the changes. @jdef 

Next my intention is to begin adding functionality for the [HTTP Operator](http://mesos.apache.org/documentation/latest/operator-http-api/).

Thanks!

**Comment by jdef** [comment]
/cc @cinchurge with respect to operator changes (I think you've already started, yes?)

@athlum w/ respect to production readiness, I think mesos 1.2 will have a more "hardened" implementation of LaunchGroup features. It's marked "experimental" in the 1.1 release for a reason.

@kevinschoon I'll make an effort to review your changes over the next week or so. FWIW there's a PR in flight for the 1.0 API already but it doesn't look like you built off any of those changes? (at least from the commit stream on your branch)

**Comment by kevinschoon** [comment]
@jdef I had not noticed your changes for 1.0.1 before. I committed [new branch](https://github.com/vektorlab/mesos-go/commits/next_mesos_11x_protos) based on those changes and did not need to modify any of your implementation. Please disregard the previous branch I had posted.

**Comment by cinchurge** [comment]
i'm in the process of merging changes for the maintenance apis from our internal branch over to github so we can make the push request here, i'll try to get it out asap

**Comment by jdef** [comment]
support for 1.1 has landed on master
