### ISSUE TITLE
pull "next" into "master" with minimal breakage for v0 API users

### ISSUE THREAD

**Issue by jdef** [mesos/mesos-go#274]
Arguably there's some benefit to maintaining the v0 APIs for a while longer: many projects use them, there's bits included in "master" that aren't supported in "next" (e.g. `detector`). At the same time, the Mesos v1 proto APIs are stable and new projects should be encouraged to build against them vs. the v0 APIs. I'm mostly happy with the "next" branch (there's still some cleanup to do around vendoring and some minor API tweaks) and the community is eager to use the APIs in "next" to build Mesos v1-based frameworks. In order to support both v0 and v1 proto APIs on mesos-go master (probably the least painful path for projects wanting to migrate from v0 to v1) I'm considering restructuring the package as follows:

```
mesos/mesos-go/pkg/v0/  (from "master" branch)
  auth/
  detector/
  examples/
  executor/
  scheduler/
  healthchecker/
  mesos/                (placeholder, should be removed)
  mesosproto/
  mesosutil/
  messenger/
  scheduler/
  testutil/
  upid/
mesos/mesos-go/pkg/v1/  (from "next" branch)
  docker/
    Dockerfile
    ...
  cmd/
    vendor/
    example-scheduler/
    example-executor/
    version.go
  lib/                  (package "mesos")
    backoff/
    encoding/
    executor/
    extras/
    httpcli/
    recordio/
    scheduler/
    time/
    *.go
mesos/mesos-go/
  Makefile              (focus on v1 targets, v0 is officially deprecated)
  ...
```

This approach allows access to both Mesos API versions (you could migrate your scheduler from v0 to v1 without breaking your executor v0 build), and doesn't prohibit the use of a service like gopkg.in.

Feedback welcome.

**Comment by kevinschoon** [comment]
That seems like a straight forward approach and easy for end users to update to. Any idea when you might get this change in?

**Comment by dhilipkumars** [comment]
Agree with the proposal, looks like it will make the scheduler migration easy.   a directory named `pkg` or `pkgs` housing a bunch of go packages will be even more intuitive than `lib`.

`v0` and `v1` looks more like an api version to me rather than pkg.  How does this look?  
```
mesos/mesos-go/api/v1/
    |
    |---docker/
    |---pkg/
        |---backoff/
        |---encoding/
        |---executor/
        |---extras/
    |---examples/        (instead of cmd ???)
    .
    .
    .
mesos/mesos-go/api/v0/  (dont change the anything in directory structure as its deprecated anyways)
    |---auth/
    |---detector/
    |---examples/
    .
    .
    .
```

**Comment by jdef** [comment]
@dhilipkumars thanks for the suggestion, I like that `api/v0` and `api/v1` clarifies the intent of the `vN` structure.

**Comment by jdef** [comment]
@kevinschoon the repackaging looks pretty straightforward. it's hard to commit to a specific timeline at the moment. I'd like to land the v1 protos in the `next` branch and then do the restructuring.

Recent feedback from the community at large has been great. It's super helpful w/ respect to bumping up the visibility and demand for a library like this. Keep it coming.

**Comment by jdef** [comment]
Currently tracking work on this branch: `jdef_unified_v0_and_v1_apis`

**Comment by dhilipkumars** [comment]
@jdef if you could break the tasks into smaller chunks, and mark _(tag)_ it for community contribution, i would like to pick some smaller ones.  If that helps.

**Comment by jdef** [comment]
@dhilipkumars see #279; there's a unit test failing (marked as TODO). Barring other blockers that arise, this is probably the only thing left that I'd like to fix before merging the restructure.

**Comment by dhilipkumars** [comment]
@jdef  is this okay?
https://github.com/mesos/mesos-go/pull/280
