### ISSUE TITLE
Proposal: Implement HTTP Operator API in "Next"

### ISSUE THREAD

**Issue by kevinschoon** [mesos/mesos-go#276]
I would like to use mesos-go to interact with the Mesos [Operator HTTP API](http://mesos.apache.org/documentation/latest/operator-http-api/). The existing "next" branch contains most of the necessary implementations, however it lacks the generated master, agent, and related protobuf code in addition to some necessary procedural code.

I have [added](https://github.com/vektorlab/mesos-go/commits/operator) a partial implementation for this and would like some feedback to see if this seems like the right direction before I continue. https://github.com/mesos/mesos-go/issues/275 has also implemented this functionality which may be useful.

Thank you for all your work on this library!

**Comment by jdef** [comment]
Thanks for this @kevinschoon, will review this week

**Comment by kevinschoon** [comment]
@jdef Looks like this can be closed and moved into https://github.com/mesos/mesos-go/issues/310.
