### ISSUE TITLE
next: document or improve handling of master disconnections

### ISSUE THREAD

**Issue by ajwerner** [mesos/mesos-go#277]
Right now the httpsched doesn't deal with disconnections from the master particularly well. Future attempts to re-subscribe on the same httpsched return errAlreadySubscribed. Currently my answer is to detect the error then mark the Context as Done and create a new httpsched. Is this the right approach? 

https://github.com/mesos/mesos-go/blob/next/httpcli/httpsched/state.go#L123

**Comment by jdef** [comment]
That's probably the best way to handle it for now. Need to carefully consider how much additional intelligence should be built into the httpsched client vs. delegating to frameworks.

**Comment by jdef** [comment]
fixed by #286
