### ISSUE TITLE
Tips on getting started with the v1 API

### ISSUE THREAD

**Issue by dstibrany** [mesos/mesos-go#296]
I'm having a hard time getting started with the v1 API. The v0 example scheduler was easier to understand and provided a nice minimal skeleton for experimenting/learning how to build frameworks.

I get that the primary goal is to provide a low-level API, but I'm wondering if anyone has any examples similar to the v0 example scheduler or tips on how I can build something similar. My initial goal is to simply register a new framework and listen for/handle events.

**Comment by jdef** [comment]
agreed. a super-simple scheduler example is needed

**Comment by jdef** [comment]
minimal scheduler example in #301

**Comment by dstibrany** [comment]
Amazing, ty.
