### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by ankurcha** [mesos/mesos-go#30]
I want to use [Sourcegraph code search](https://sourcegraph.com) with mesos-go. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable mesos-go on @Sourcegraph by going to https://sourcegraph.com/github.com/mesos/mesos-go and clicking on Settings? (It should only take 15 seconds.)

It really helps when I am navigating source and would be highly appreciated.

**Comment by vladimirvivien** [comment]
Already done.
