### ISSUE TITLE
LaunchNestedContainer and agent.proto in 1.2.x

### ISSUE THREAD

**Issue by athlum** [mesos/mesos-go#309]
Hi.
According to https://github.com/apache/mesos/blob/master/docs/nested-container-and-task-group.md#new-agent-api. To implement TaskGroup, we need the go-compiled https://github.com/apache/mesos/blob/1.2.x/include/mesos/agent/agent.proto file at least.
Do you guys have any plans on LaunchGroup? It is so great that we have go sdk for mesos-1.2.x now.

Thanks for any reply.

**Comment by jdef** [comment]
If you want to launch a pod you don't need the agent API, you can use the
LAUNCH_GROUP operation upon accepting offers from the framework:
https://github.com/apache/mesos/blob/1.2.x/include/mesos/v1/mesos.proto#L1439

Or, are you trying to do something more complicated with the agent API? If
so, I started hacking on agent API support (#308) and bumped into a few
small issues, nothing major. Hoping to wrap it up sooner than later.
