### ISSUE TITLE
The taskid in status update is empty after call task kill. 

### ISSUE THREAD

**Issue by vulcan-lin** [mesos/mesos-go#315]
Exiting because task  is in an unexpected state TASK_LOST with reason REASON_RECONCILIATION from source SOURCE_MASTER with message 'Reconciliation: Task is unknown'

mesos 1.3.0
mesos-go v1(commit id:464c8d6a7d891b5f7695e6a6e78c6e3974223db4)

**Comment by jdef** [comment]
Thanks for reporting this. Can you provide some additional context around this? For example, how might someone reproduce this error? Was this observed with the example scheduler/executor, or with a custom framework that you developed?

**Comment by vulcan-lin** [comment]
Sorry for the late reply.
I write a custom framework base on the msh.
This not a bug because I given a wrong task id that  not exist in mesos tasks list.

**Comment by jdef** [comment]
Thanks for the update. I'll close this out. Please re-open if needed.
