### ISSUE TITLE
Dynamic Commands in TaskInfo

### ISSUE THREAD

**Issue by webdev** [mesos/mesos-go#44]
How do you define a dynamic command in ```mesos.taskInfo```?

I'm trying to change a definition mesos.TasksInfo from using an executor, to executing any command.

I see the command being executed but getting a SegFault right away.

```go
&mesos.TaskInfo{
				Name: proto.String("go-task"),
				TaskId: &mesos.TaskID{
					Value: proto.String("go-task-" + strconv.Itoa(s.taskId)),
				},
				SlaveId:  offer.SlaveId,
				//Executor: executor,
				Command: &mesos.CommandInfo{
					Value: proto.String("echo $((1+1))"),
				},
				Resources: []*mesos.Resource{
					mesos.ScalarResource("cpus", 1),
					mesos.ScalarResource("mem", 512),
				},
			},
```

Any tips?

**Comment by vladimirvivien** [comment]
@webdev Is this still an issue for you or did you figure it out ?
