### ISSUE TITLE
Scheduler is announcing itself on 0.0.0.0

### ISSUE THREAD

**Issue by bobrik** [mesos/mesos-go#52]
This is follow-up from #46.

[This](https://github.com/mesos/mesos-go/blob/2c1f1b23c487a241b03e6d5bac58589d98be933e/messenger/http_transporter.go#L35) is [not true](https://github.com/mesos/mesos-go/blob/2c1f1b23c487a241b03e6d5bac58589d98be933e/messenger/http_transporter.go#L103-L104), `0.0.0.0` is "all ips", not localhost. Because of this mesos cannot reach back to scheduler and framework cannot register itself. This probably works on localhost, but does not work with 3 masters on different hosts.

I think we should pass `upid.UPID` into `scheduler.NewMesosSchedulerDriver` to make it more flexible.

**Comment by vladimirvivien** [comment]
@bobrik So, to clarify, you are suggesting to provide a way to specify an address to bind the scheduler to?

**Comment by bobrik** [comment]
@vladimirvivien yes, exactly.

**Comment by vladimirvivien** [comment]
@bobrik I opened a ticket for your suggestion and closing this one.
