### ISSUE TITLE
Executor startup broken

### ISSUE THREAD

**Issue by diptanu** [mesos/mesos-go#72]
Hi,

I just pulled master, and saw that my executor doesn't start up anymore. This executor used to startup until a few weeks back. 

E0208 02:08:22.506744   15178 http_transporter.go:128] HTTPTransporter failed to listen: listen tcp4: unknown port tcp4/

E0208 02:08:22.507236   15178 messenger.go:150] Failed to start messenger: listen tcp4: unknown port tcp4/

E0208 02:08:22.507247   15178 executor.go:388] Failed to start executor: listen tcp4: unknown port tcp4/

@vladimirvivien Do you have any suggestions?

**Comment by fmpwizard** [comment]
I think it's related to now needing to specify the port number https://github.com/mesos/mesos-go/pull/69

**Comment by diptanu** [comment]
@fmpwizard @vladimirvivien Doesn't look right to me. It's not possible to specify a port for an executor as far as i know. The Mesos slave invokes the executor.

**Comment by diptanu** [comment]
@vladimirvivien I think the behavior on #69 should be use the host and port that user has specified but if not, then just bind to random port and listen on all interfaces.

**Comment by diptanu** [comment]
@vladimirvivien ping

I could send you an PR for you to review. This is basically blocking us from using mesos-go for replacing our java based executor.

**Comment by vladimirvivien** [comment]
@diptanu please send PR.

**Comment by diptanu** [comment]
@vladimirvivien Sent a PR your way :)

**Comment by jdef** [comment]
xref #88
