### ISSUE TITLE
Add continuous build.

### ISSUE THREAD

**Issue by vladimirvivien** [mesos/mesos-go#77]

**Comment by fmpwizard** [comment]
would using something like https://travis-ci.com/ work for this project? they specifically support Go and godep http://docs.travis-ci.com/user/languages/go/

**Comment by vladimirvivien** [comment]
@fmpwizard yes. I have also used drone.io before. Either would work.

**Comment by fmpwizard** [comment]
cool, I may be able to work on this over the weekend
