### ISSUE TITLE
test framework starts taskCount + 1 mesos tasks

### ISSUE THREAD

**Issue by fmpwizard** [mesos/mesos-go#87]
if you run the example framework and executor and pass the `-task-count=2` value, mesos ends up running 3 tasks instead of two.

I see this by looking at the logs and I see:

```
...Prepared task: go-task-1...
...Prepared task: go-task-2...
...Prepared task: go-task-3...
```

The error seems on this file
https://github.com/mesos/mesos-go/blob/master/examples/test_framework.go#L109

```
for sched.tasksLaunched <= sched.totalTasks &&
```
if I change it to

```
for sched.tasksLaunched < sched.totalTasks &&
```

then it only schedules the number of tasks  I passed on the command line.

If you agree this is an issue, I can send a quick PR to fix it.

Thanks

**Comment by jdef** [comment]
Sounds like a bug to me. PR welcome

**Comment by fmpwizard** [comment]
tnx, PR sent
