### ISSUE TITLE
extract auth, host, and port flags for scheduler, executor into config structs

### ISSUE THREAD

**Issue by jdef** [mesos/mesos-go#88]
Instead of burying flags inside the bindings library, we should leave that to the actual framework schedulers and executors. Instead, modify the driver constructors to accept config structs. This is way more flexible and allows for easier testing and experimentation with other types of transports, for example TLS.

For example:

```go
package scheduler

type DriverConfig {
  NewMessenger func() (messenger.Messenger,error)
  AuthProvider string
  Scheduler Scheduler
  Framework *mesos.FrameworkInfo
  Master string
  Credential *mesos.Credential
}

func NewMesosSchedulerDriver(config DriverConfig) (*MesosSchedulerDriver, error) {
  // ...
  driver.messenger, err = config.NewMessenger()
  //...
}
```

```go
package messenger

func NewHttpFactory(host string, port int) (func() (Messenger, error)) {
  return func() (Messenger, error) {
    upid := &upid.UPID{
		ID:   "scheduler(1)",
		Host: host,
		Port: strconv.Itoa(port),
	}
    return NewHttp(upid), nil
  }
}
```

```go
package main

import (
  "flag"
  //...
)

var (
  hostFlag := flag.String(...)
  portFlag := flag.Int(...)
  authProviderFlag := flag.String(...)
)

// run some framework
func main() {
  config := DriverConfig{
    NewMessenger: messenger.NewHttpFactory(*hostFlag, *portFlag),
    AuthProvider: *authProviderFlag,
    // ... other config here
  }
  driver, err := scheduler.NewMesosSchedulerDriver(config)
  //...
}
```

**Comment by razic** [comment]
damn it this bit me in the ass

**Comment by jdef** [comment]
Is there a specific problem to this approach that you're experiencing?

On Tue, Mar 10, 2015 at 2:07 PM, Zachary Adam Kaplan <
notifications@github.com> wrote:

> damn it this bit me in the ass
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesos/mesos-go/issues/88#issuecomment-78112456>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by razic** [comment]
nope, i dont vendor my dependencies or use a dependency manager like `godeps`, so when i `go get -v ./...` it installs from HEAD and then my code broke because of the DSL modifications.
