### ISSUE TITLE
git merge style

### ISSUE THREAD

**Issue by chrisjs** [mesos/mesos-go#96]
i noticed when PR's get accepted, there are merge commits. as a suggestion to keep the git log a bit more tidy, possibly consider fast forward merges only (i.e. git merge --ff-only <BRANCH_TO_MERGE>)?

**Comment by jdef** [comment]
Thanks for the suggestion. FWIW the git logs you've observed are a direct result of the github tooling processing a *merge-this-PR* operation. We can certainly consider fast-forward only merges. Though the convenience of clicking "Merge PR" in github is often too tempting.

**Comment by chrisjs** [comment]
understood about the gh click to merge. while it takes a little more for ff merges, keeps things cleaner and easier to look through. 

going to close the issue, just wanted to raise an observation about the repo logs

**Comment by philosoralphter** [comment]
Alternatively, a git rebase workflow is very effective. Slightly more difficult to get people to do correctly but you get clean flat logs and github merges work fine when each committer rebases their work right before pushing and PRing.
